version: '3'
services:
  mongo:
    image: mongo:4.2
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
  sd:
    image: koumoul/simple-directory:master
    network_mode: host
    environment:
      - DEBUG=webhooks
      - ADMINS=["alban.mouton@koumoul.com", "superadmin@test.com"]
      - PUBLIC_URL=http://localhost:5608/simple-directory
      - MAILDEV_ACTIVE=true
      - STORAGE_TYPE=file
      #- STORAGE_TYPE=mongo
      - STORAGE_MONGO_URL=mongodb://localhost:27017/simple-directory
      - NUXT_BUILD_BLOCKING=false
      - LIST_ENTITIES_MODE=anonymous
      - NO_UI=${NO_UI}
      - AUTHRATELIMIT_ATTEMPTS=200
      - DEFAULT_MAX_CREATED_ORGS=10
    volumes:
      - ./test/resources/users.json:/webapp/data/users.json
      - ./test/resources/organizations.json:/webapp/data/organizations.json

  openapi-viewer:
    image: koumoul/openapi-viewer:1
    ports:
      - 5680:8080

  notify:
    image: ghcr.io/data-fair/notify:master
    network_mode: host
    environment:
      - PORT=8088
      - PUBLIC_URL=http://localhost:5608/notify
      - WS_PUBLIC_URL=ws://localhost:5608/notify
      - DIRECTORY_URL=http://localhost:5608/simple-directory
      - SECRET_NOTIFICATIONS=secret-notifications
      - SECRET_SENDMAILS=secret-sendmails

volumes:
  mongo-data:
